name: Build

permissions:
  contents: write
  packages: write

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.os }} (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            name: linux-x86_64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            name: linux-aarch64
          - os: macos-latest
            target: aarch64-apple-darwin
            name: macos-aarch64
          - os: macos-latest
            target: x86_64-apple-darwin
            name: macos-x86_64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            name: windows-x86_64
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            name: windows-aarch64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          if [ "${{ matrix.target }}" = "aarch64-unknown-linux-gnu" ]; then
            sudo dpkg --add-architecture arm64
            sudo sed -i 's/Types: deb/Types: deb\nArchitectures: amd64/g' /etc/apt/sources.list.d/ubuntu.sources
            
            echo -e "Types: deb\nArchitectures: arm64\nURIs: http://ports.ubuntu.com/ubuntu-ports\nSuites: noble noble-updates noble-backports noble-security\nComponents: main universe restricted multiverse" | sudo tee /etc/apt/sources.list.d/ubuntu-ports.sources
            
            sudo apt-get update
            sudo apt-get install -y gcc-aarch64-linux-gnu libc6-dev-arm64-cross pkg-config libasound2-dev:arm64 libclang-dev
            
            echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
            echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV
            echo "PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig" >> $GITHUB_ENV
          else
            sudo apt-get update
            sudo apt-get install -y libasound2-dev libclang-dev pkg-config
          fi

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cargo-bundle (macOS)
        if: startsWith(matrix.os, 'macos')
        run: cargo install cargo-bundle

      - name: Build macOS App Bundle & DMG
        if: startsWith(matrix.os, 'macos')
        run: |
          cargo bundle --release --format osx --target ${{ matrix.target }}
          APP_PATH="target/${{ matrix.target }}/release/bundle/osx/Slyh.app"
          
          DMG_NAME="slyh-${{ matrix.name }}.dmg"
          hdiutil create -volname "Slyh" -srcfolder "$APP_PATH" -ov -format UDZO "$DMG_NAME"

      - name: Build binary (Windows/Linux)
        if: "!startsWith(matrix.os, 'macos')"
        run: cargo build --release --locked --target ${{ matrix.target }}

  build-deb:
    name: Build Debian Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libclang-dev

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-bundle
        run: cargo install cargo-bundle

      - name: Build .deb
        run: cargo bundle --release --format deb

  flatpak-build:
    name: Build Flatpak
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-24.08
      options: --privileged

    steps:
      - uses: actions/checkout@v4

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: ru.arabianq.slyh.flatpak
          manifest-path: packages/flatpak/ru.arabianq.slyh.yaml
          cache: true
          branch: master
          build-bundle: true